# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e6e881ce5a3ec97a630b28c97342c35c6f1315f2785ae68a709972bd47622b3f767f5534f629bf9f916edc432f40598d5bea5c54440790fa26ab060e09851cb

test:
  secret_key_base: b8069f1fe8e42a9dd1ad259d8ec9608c10c06498ec1ce7bd89d07554ac28b38cb32276e055e3cf9d6c23d62e15b74458411416cea3d7c6e7284d8ccc65693dd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
